In [4]:
!pip install apyori

Requirement already satisfied: apyori in c:\users\admin\anaconda3\lib\site-packages (1.1.2)

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv('Market_Basket_Optimization.csv', header = None)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
transactions= []
for i in range(0 ,7051):
    transactions.append([str(df.values[i,j]) for j in range(0,20)])

In [8]:
from apyori import apriori
rules = apriori(transactions = transactions , min_support = 0.003 , min_confidence = 0.2, min_lift = 3 , min_length = 2 , max_length = 2)

In [9]:
results = list(rules)
results

[RelationRecord(items=frozenset({'burgers', 'almonds'}), support=0.005531130336122536, ordered_statistics=[OrderedStatistic(items_base=frozenset({'almonds'}), items_add=frozenset({'burgers'}), confidence=0.2671232876712329, lift=3.102942835864684)]),
 RelationRecord(items=frozenset({'chicken', 'light cream'}), support=0.004396539497943554, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.28703703703703703, lift=4.73980830948044)]),
 RelationRecord(items=frozenset({'mushroom cream sauce', 'escalope'}), support=0.005814778045667281, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.30597014925373134, lift=3.8593837609804287)]),
 RelationRecord(items=frozenset({'pasta', 'escalope'}), support=0.00524748262657779, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.3737373737373737, lift=4.714172132776784)]),
 RelationRecord(items=frozenset({'honey', 'fromage blanc'}), support=0.0035455963693093178, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'honey'}), confidence=0.27777777777777773, lift=5.726933073424301)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'parmesan cheese'}), support=0.005389306481350163, ordered_statistics=[OrderedStatistic(items_base=frozenset({'parmesan cheese'}), items_add=frozenset({'frozen vegetables'}), confidence=0.2900763358778626, lift=3.048179201601802)]),
 RelationRecord(items=frozenset({'herb & pepper', 'ground beef'}), support=0.015742447879733373, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3226744186046512, lift=3.2689329390537294)]),
 RelationRecord(items=frozenset({'tomato sauce', 'ground beef'}), support=0.00524748262657779, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.3737373737373737, lift=3.786238825031928)]),
 RelationRecord(items=frozenset({'olive oil', 'light cream'}), support=0.0032619486597645726, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.21296296296296297, lift=3.222321570497536)]),
 RelationRecord(items=frozenset({'whole wheat pasta', 'olive oil'}), support=0.007658488157708127, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2621359223300971, lift=3.9663527646985286)]),
 RelationRecord(items=frozenset({'pasta', 'shrimp'}), support=0.0035455963693093178, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.2525252525252525, lift=3.491285403050108)])]

In [10]:
def inspect(results):
    lhs = [tuple(result[2][0][0])[0] for result in results]
    rhs = [tuple(result[2][0][1])[0] for result in results]
    supports = [result[1] for result in results]
    confidence = [result[2][0][2] for result in results]
    lifts = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports))
resultsindataframe = pd.DataFrame(inspect(results), columns = ['lhs', 'rhs', 'supports' ] )
resultsindataframe

                     lhs                rhs  supports
0                almonds            burgers  0.005531
1            light cream            chicken  0.004397
2   mushroom cream sauce           escalope  0.005815
3                  pasta           escalope  0.005247
4          fromage blanc              honey  0.003546
5        parmesan cheese  frozen vegetables  0.005389
6          herb & pepper        ground beef  0.015742
7           tomato sauce        ground beef  0.005247
8            light cream          olive oil  0.003262
9      whole wheat pasta          olive oil  0.007658
10                 pasta             shrimp  0.003546

In [13]:
resultsindataframe.nlargest(n = 10 , columns='supports')

                     lhs                rhs  supports
6          herb & pepper        ground beef  0.015742
9      whole wheat pasta          olive oil  0.007658
2   mushroom cream sauce           escalope  0.005815
0                almonds            burgers  0.005531
5        parmesan cheese  frozen vegetables  0.005389
3                  pasta           escalope  0.005247
7           tomato sauce        ground beef  0.005247
1            light cream            chicken  0.004397
4          fromage blanc              honey  0.003546
10                 pasta             shrimp  0.003546